services: docker
language: python
python:
  - "3.6"

env:
  matrix:
    - ARCH=i386
    - ARCH=amd64
    - ARCH=arm
    - ARCH=armv7
    - ARCH=aarch64

install:
  - pip install -r requirements-test.txt

before_script:
  - ./build.sh $ARCH
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - pytest -v test.py
  - docker build -t robertbeal/flickr:$ARCH -t robertbeal/flickr:$ARCH.$VERSION --file Dockerfile.$ARCH .

deploy:
  provider: script
  script:
    echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin &&
    docker push robertbeal/flickr:$ARCH;
  on:
    branch: master
